
desc "Bump version for both Android and iOS"
lane :bump_version do |options|
  version_type = options[:version_type] || "patch" # Default to "patch" if not provided

  # Bump version in package.json using Yarn
  begin
    new_version = sh("yarn version --#{version_type} --no-git-tag-version").strip.match(/"version": "(.*?)"/)[1]
  rescue => e
    UI.error("Failed to bump version: #{e.message}")
    raise
  end
  sh("echo #{new_version} > .version")

  # Bump iOS version
  increment_version_number(version_number: new_version)
  increment_build_number

  # Bump Android version
  gradle_file = "./android/app/build.gradle"
  android_version_code = get_version_code_from_gradle(gradle_file: gradle_file).to_i + 1
  android_version_name = new_version
  update_gradle_property(
    property: "versionCode",
    value: android_version_code.to_s,
    gradle_file: gradle_file
  )
  update_gradle_property(
    property: "versionName",
    value: "\"#{android_version_name}\"",
    gradle_file: gradle_file
  )

  UI.message("Bumped version to #{new_version}")
end
